Repository Android-Team-13-Maniacs/android_project_maniacs, pull requests merged in 2023-09, with the labels that each got.

#6 VideoItem layout 구현
  app/src/main/java/com/example/android_teammaniacs_project/data/Reply.kt
  app/src/main/java/com/example/android_teammaniacs_project/data/Video.kt
  app/src/main/res/layout/video_item.xml
  app/src/main/res/values/strings.xml
Labels: Design

#8 [DESIGN] : 🎨 Mainactivity UI
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_teammaniacs_project/MainActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/Test1Fragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/Test2Fragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/Test3Fragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/main/MainActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/main/MainTabs.kt
  app/src/main/java/com/example/android_teammaniacs_project/main/MainViewPagerAdapter.kt
  app/src/main/res/color/selector_tablayout.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_myvideos.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/fragment_test1.xml
  app/src/main/res/layout/fragment_test2.xml
  app/src/main/res/layout/fragment_test3.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Design

#10 [DESIGN] : 🎨 MyVideoFragment layout 구현
  app/build.gradle
  app/src/main/java/com/example/android_teammaniacs_project/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/res/drawable/ic_profile_image.xml
  app/src/main/res/layout/my_video_fragment.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: Design

#11 Design/homefragment
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_teammaniacs_project/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/adapters/HomeBannerAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/adapters/HomeVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/main/MainViewPagerAdapter.kt
  app/src/main/res/drawable-nodpi/example_appwidget_preview.png
  app/src/main/res/drawable-v21/app_widget_background.xml
  app/src/main/res/drawable-v21/app_widget_inner_view_background.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_banner_item.xml
  app/src/main/res/layout/home_spinner_item.xml
  app/src/main/res/values-night-v31/themes.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values-v31/styles.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: Feature, Design

#12 [DESIGN] : Searchfragment layout
  app/src/main/java/com/example/android_teammaniacs_project/main/SearchAdapter.kt
  app/src/main/res/drawable/btn_search.xml
  app/src/main/res/drawable/img_search.xml
  app/src/main/res/layout/fragment_test2.xml
  app/src/main/res/layout/search_item.xml
Labels: Design

#13 Design/videodetailactivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_teammaniacs_project/data/Reply.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/CommentListAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/CommentModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/res/drawable/dog.jpeg
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_heart_fill.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/muhandojeon.png
  app/src/main/res/layout/coment_item.xml
  app/src/main/res/layout/video_detail_activity.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: Design

#18 [FEAT] : ⚙️ Search RecyclerView Adapter 구현
  app/src/main/java/com/example/android_teammaniacs_project/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
Labels: Feature

#22 [DESIGN] : 🎨 | 각 버튼 커스텀 하기
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/res/layout/video_detail_activity.xml
Labels: Design

#23 [DESIGN] : 🎨 | 각 버튼 커스텀 하기(2)
  app/src/main/res/drawable/add_selector.xml
  app/src/main/res/drawable/like_selector.xml
Labels: Design

#24 Feature/fragment_item
  app/build.gradle
  app/src/main/java/com/example/android_teammaniacs_project/data/Video.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/res/layout/video_item.xml
Labels: Feature

#28 Design/detail effect
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/res/drawable/fade_in.xml
  app/src/main/res/drawable/fade_out.xml
Labels: Design

#29 [FEAT] : ⚙️ Home Itme Click
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeBannerAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeVideoAdapter.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/home_banner_item.xml
Labels: Feature

#33 [FEAT] : ⚙️ | 각 버튼 클릭시 토스트 메세지 추가하기
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
Labels: Feature

#35 [FEAT] : ⚙️ SearchFragment 검색 기능 구현
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_teammaniacs_project/constants/Constants.kt
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/PopularVideoModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/SearchVideoModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModelFactory.kt
Labels: Feature

#36 Refactor/mvvm
  app/src/main/java/com/example/android_teammaniacs_project/data/Video.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVidelViewModelFactory.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
  app/src/main/res/layout/home_banner_item.xml
  app/src/main/res/layout/video_item.xml
Labels: Refactor

#37 [FIX] : 🔧 | viewmodel greadle 추가
  app/build.gradle
Labels: Fix

#38 [FIX] : 🔧 | 홈 mvvm 누락 내용 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeBannerAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModelFactory.kt
Labels: Fix

#39 [DESIGN] : 🎨SearchFragment UI 수정
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: Design

#41 [FEAT] : ⚙️ Home banner API 연동
  app/src/main/java/com/example/android_teammaniacs_project/data/Category.kt
  app/src/main/java/com/example/android_teammaniacs_project/data/Video.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/CommentListAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/CommentModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeBannerAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModelFactory.kt
  app/src/main/java/com/example/android_teammaniacs_project/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVidelViewModelFactory.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/CategoryModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/PopularVideoModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/SearchVideoModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModelFactory.kt
  app/src/main/res/layout/comment_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/home_banner_item.xml
  app/src/main/res/layout/home_spinner_item.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/video_detail_activity.xml
  app/src/main/res/layout/video_item.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#46 [FEAT] : ⚙️ 선택 기준 별 Search 기능 구현
  app/src/main/java/com/example/android_teammaniacs_project/constants/SearchButtonType.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: Feature

#48 [FEAT] : ⚙️ | DetailActivity에서 값 보여주기
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
Labels: Feature

#52 [Feature]: HomeFragment Spinner 구현
  app/build.gradle
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
  app/src/main/res/layout/home_spinner_item.xml
Labels: Feature

#53 [DOCS] : 📚 Retrofit 관련 주석 추가
  app/src/main/java/com/example/android_teammaniacs_project/constants/Constants.kt
  app/src/main/java/com/example/android_teammaniacs_project/constants/SearchButtonType.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/CategoryModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/PopularVideoModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/SearchVideoModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
Labels: Docs

#54 [FIX] : 🔧 viewpager slide
  app/src/main/java/com/example/android_teammaniacs_project/main/MainActivity.kt
Labels: Fix

#55 [FEAT] : ⚙️ | My list 추가 기능
  app/build.gradle
  app/src/main/java/com/example/android_teammaniacs_project/constants/Constants.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
Labels: Feature

#57 [Backup] 0929 Main Backup
  app/build.gradle
  app/src/main/java/com/example/android_teammaniacs_project/constants/Constants.kt
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/constants/SearchButtonType.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/main/MainActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/CategoryModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/PopularVideoModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/SearchVideoModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/home_spinner_item.xml
Labels: Backup

#58 [FEAT] : ⚙️ Category 별 영상 기능 상단 구현
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/CategoryModel.kt
Labels: Feature

#63 [FEAT] : ⚙️ HomeFragment 아래 Spinner 구현
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: Feature
