Repository Android-Team-13-Maniacs/android_project_maniacs, pull requests merged in 2023-10, with the labels that each got.

#65 [FIX] : 🔧 HomeFragment 수정
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
Labels: Fix

#69 code refactoring
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeBannerAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/res/drawable-v21/app_widget_inner_view_background.xml
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/img_loding.png
  app/src/main/res/drawable/img_no.png
  app/src/main/res/drawable/spinner_selector.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/my_video_fragment.xml
  app/src/main/res/layout/video_detail_activity.xml
  app/src/main/res/layout/video_item.xml
Labels: Refactor

#71 SearchFragment InfinityScroll 구현
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
Labels: Feature

#73 Fix/mylist
  app/src/main/java/com/example/android_teammaniacs_project/constants/Constants.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
Labels: Fix

#74 Design/home banner
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/res/drawable/btn_slide.xml
  app/src/main/res/drawable/fill_circle.xml
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/img_floating_nor.png
  app/src/main/res/drawable/img_floating_press.png
  app/src/main/res/drawable/stoke_circle.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/home_banner_item.xml
  app/src/main/res/layout/home_spinner_item.xml
  app/src/main/res/layout/video_item.xml
Labels: Feature, Design

#77 [FIX] : 🔧 | 공유하기 기능 수정
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
Labels: Fix

#78 Infinite Scroll 기능 수정
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
Labels: Fix

#80 [FEAT] : ⚙️ banner indecator
  app/build.gradle
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/SnapPagerScrollListener.kt
  app/src/main/res/layout/fragment_home.xml
Labels: Feature

#81 [Feature]: SearchFragment 오류 및 예외 처리
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/NoResultsException.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
Labels: Feature

#84 [FIX] : 🔧 home banner 인디케이터 위치 수정
  app/src/main/res/layout/fragment_home.xml
Labels: Fix

#88 Detail Fragment 수정
  app/build.gradle
  app/src/main/java/com/example/android_teammaniacs_project/data/Video.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/utils/Utils.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/video_detail_activity.xml
Labels: Fix

#90 SearchFragment Refactoring
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/NoResultsException.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
Labels: Refactor

#92 Detail Page 채널 이미지 추가
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/CommentListAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/CommentModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailViewModelFactory.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/ChannelModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
  app/src/main/res/layout/video_detail_activity.xml
Labels: Refactor, Feature, Design

#94 Feature/text
  app/build.gradle
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/my_video_fragment.xml
Labels: Feature

#95 Home Fragment 카테고리 별 채널 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_teammaniacs_project/data/Channel.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeChannelAdapter.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: Refactor, Feature

#96 [FEAT] : ⚙️ Nullpoint Exception 예외처리
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
  app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
Labels: Feature

#98 Feature/edit mypage
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/ProfileDialog.kt
  app/src/main/res/drawable/edit_selector.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_save.xml
  app/src/main/res/drawable/stoke_circle.xml
  app/src/main/res/layout/dialog_edit.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/my_video_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#101 [FIX] : 🔧 무한 스크롤 기능 수정
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
Labels: Fix

#103 [FIX] : 🔧 edit page
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
Labels: Fix

#104 [FIX] : SearchFragment Floating Button Visibility 수정
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/res/layout/fragment_search.xml
Labels: Fix

#105 MyVideoFragment sharedPreferences 기능
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
  app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/ProfileDialog.kt
Labels: Feature

#106 발표 전 수정 내용
  app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
  app/src/main/res/layout/my_video_fragment.xml
Labels: Fix
